/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mancala;

import java.awt.Component;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;

/**
 *
 * @author iago-
 */
public class Board extends javax.swing.JPanel {

    /**
     * Creates new form Board
     */
    private Mancala mancala;
    private JLabel[] pieces;
    private int[] startingX = new int[48];
    private int[] startingY = new int[48];
    
    public Board() {
        initComponents();
        this.pieces = registerPieces(this.jLayeredPane2.getComponents());
        this.namePieces(this.pieces);
        
    }
    
    public JLabel[] getPieces(){
        return this.pieces;
    }
    
    public JLabel getPiece(int n){
        return this.pieces[n];
    }
    
    public void setPiece(int n, int x, int y){
        this.getPiece(n).setLocation(x, y);
    }
    
    public void appendChat(String msg){
        this.jTextArea1.append(msg+"\n");
    }
    
    private void addMovement(Component[] arr){
        Movement move = new Movement(arr, this.mancala);
    }
    
    private JLabel[] registerPieces(Component[] arr){
        JLabel[] labs = new JLabel[48];
        for(int i=0; i<arr.length; i++){
            if(arr[i] instanceof JLabel){
               labs[i] = (JLabel) arr[i];
               this.startingX[i] = labs[i].getX();
               this.startingY[i] = labs[i].getY();
            }
        }
        return labs;
    }
    
    private void resetBoard(){
        for(int i=0; i<this.pieces.length; i++){
            this.setPiece(i, this.startingX[i], this.startingY[i]);
        }
    }
    
    private void namePieces(JLabel[] arr){
        int i=0;
        for(JLabel j : arr){
            j.setName(Integer.toString(i));
            i++;
        }
    }
    
    public void setTurn(String turn){
        this.turnLabel.setText(turn);
    }
    
    public String getTurn(){
        return this.turnLabel.getText();
    }
    
    public void setPlayerName(String name){
        this.playerLabel.setText(name);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        chatTextField = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        onlineCheckbox = new javax.swing.JCheckBox();
        jPanel5 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        hostField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        portField = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        hostNameLabel = new javax.swing.JLabel();
        restartButton = new javax.swing.JButton();
        statusPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        playerLabel = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        turnLabel = new javax.swing.JLabel();
        endTurnButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        mainPanel1 = new mancala.MainPanel();
        jLabel54 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel56 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jLabel1.setText("Chat");

        chatTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chatTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(chatTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Chat", jPanel2);

        onlineCheckbox.setText("Online");
        onlineCheckbox.setEnabled(false);

        jLabel4.setText("Host:");

        hostField.setText("localhost");

        jLabel5.setText("Port:");

        jButton2.setText("Conectar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel6.setText("Local server");

        restartButton.setText("Reiniciar Partida");
        restartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restartButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(portField, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                            .addComponent(hostField)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jLabel6)
                            .addComponent(hostNameLabel)
                            .addComponent(restartButton))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(hostField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hostNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(restartButton)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(onlineCheckbox)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(onlineCheckbox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Menu", jPanel3);

        statusPanel.setLayout(new java.awt.GridLayout(3, 2, 3, 0));

        jLabel3.setText("Jogador");
        statusPanel.add(jLabel3);
        statusPanel.add(playerLabel);

        jLabel58.setText("Turno");
        statusPanel.add(jLabel58);
        statusPanel.add(turnLabel);

        endTurnButton.setText("Encerrar turno");
        endTurnButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endTurnButtonActionPerformed(evt);
            }
        });
        statusPanel.add(endTurnButton);

        jButton5.setText("Render-se");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        statusPanel.add(jButton5);

        jLayeredPane2.setMinimumSize(new java.awt.Dimension(1026, 384));
        jLayeredPane2.add(mainPanel1);
        mainPanel1.setBounds(0, 0, 1030, 382);

        jLabel54.setForeground(new java.awt.Color(51, 204, 0));
        jLabel54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel54.setOpaque(true);
        jLabel54.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel54, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel54);
        jLabel54.setBounds(820, 120, 25, 25);

        jLabel51.setForeground(new java.awt.Color(51, 204, 0));
        jLabel51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel51.setOpaque(true);
        jLabel51.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel51, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel51);
        jLabel51.setBounds(770, 80, 25, 25);

        jLabel52.setForeground(new java.awt.Color(51, 204, 0));
        jLabel52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel52.setOpaque(true);
        jLabel52.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel52, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel52);
        jLabel52.setBounds(820, 80, 25, 25);

        jLabel53.setForeground(new java.awt.Color(51, 204, 0));
        jLabel53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel53.setOpaque(true);
        jLabel53.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel53, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel53);
        jLabel53.setBounds(770, 120, 25, 25);

        jLabel34.setForeground(new java.awt.Color(51, 204, 0));
        jLabel34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel34.setOpaque(true);
        jLabel34.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel34, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel34);
        jLabel34.setBounds(660, 280, 25, 25);

        jLabel32.setForeground(new java.awt.Color(51, 204, 0));
        jLabel32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel32.setOpaque(true);
        jLabel32.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel32, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel32);
        jLabel32.setBounds(810, 240, 25, 25);

        jLabel33.setForeground(new java.awt.Color(51, 204, 0));
        jLabel33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel33.setOpaque(true);
        jLabel33.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel33, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel33);
        jLabel33.setBounds(660, 240, 25, 25);

        jLabel55.setForeground(new java.awt.Color(51, 204, 0));
        jLabel55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel55.setOpaque(true);
        jLabel55.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel55, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel55);
        jLabel55.setBounds(700, 240, 25, 25);

        jLabel47.setForeground(new java.awt.Color(51, 204, 0));
        jLabel47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel47.setOpaque(true);
        jLabel47.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel47, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel47);
        jLabel47.setBounds(650, 80, 25, 25);

        jLabel50.setForeground(new java.awt.Color(51, 204, 0));
        jLabel50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel50.setOpaque(true);
        jLabel50.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel50, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel50);
        jLabel50.setBounds(700, 120, 25, 25);

        jLabel45.setForeground(new java.awt.Color(51, 204, 0));
        jLabel45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel45.setOpaque(true);
        jLabel45.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel45, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel45);
        jLabel45.setBounds(700, 280, 25, 25);

        jLabel46.setForeground(new java.awt.Color(51, 204, 0));
        jLabel46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel46.setOpaque(true);
        jLabel46.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel46, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel46);
        jLabel46.setBounds(540, 280, 25, 25);

        jLabel44.setForeground(new java.awt.Color(51, 204, 0));
        jLabel44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel44.setOpaque(true);
        jLabel44.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel44, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel44);
        jLabel44.setBounds(540, 240, 25, 25);

        jLabel43.setForeground(new java.awt.Color(51, 204, 0));
        jLabel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel43.setOpaque(true);
        jLabel43.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel43, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel43);
        jLabel43.setBounds(580, 280, 25, 25);

        jLabel36.setForeground(new java.awt.Color(51, 204, 0));
        jLabel36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel36.setOpaque(true);
        jLabel36.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel36, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel36);
        jLabel36.setBounds(420, 280, 25, 25);

        jLabel41.setForeground(new java.awt.Color(51, 204, 0));
        jLabel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel41.setOpaque(true);
        jLabel41.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel41, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel41);
        jLabel41.setBounds(460, 280, 25, 25);

        jLabel56.setForeground(new java.awt.Color(51, 204, 0));
        jLabel56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel56.setOpaque(true);
        jLabel56.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel56, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel56);
        jLabel56.setBounds(420, 240, 25, 25);

        jLabel35.setForeground(new java.awt.Color(51, 204, 0));
        jLabel35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel35.setOpaque(true);
        jLabel35.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel35, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel35);
        jLabel35.setBounds(580, 240, 25, 25);

        jLabel27.setForeground(new java.awt.Color(51, 204, 0));
        jLabel27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel27.setOpaque(true);
        jLabel27.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel27, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel27);
        jLabel27.setBounds(470, 80, 25, 25);

        jLabel24.setForeground(new java.awt.Color(51, 204, 0));
        jLabel24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel24.setOpaque(true);
        jLabel24.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel24, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel24);
        jLabel24.setBounds(530, 80, 25, 25);

        jLabel25.setForeground(new java.awt.Color(51, 204, 0));
        jLabel25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel25.setOpaque(true);
        jLabel25.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel25, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel25);
        jLabel25.setBounds(580, 80, 25, 25);

        jLabel26.setForeground(new java.awt.Color(51, 204, 0));
        jLabel26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel26.setOpaque(true);
        jLabel26.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel26, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel26);
        jLabel26.setBounds(420, 80, 25, 25);

        jLabel16.setForeground(new java.awt.Color(51, 204, 0));
        jLabel16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel16.setName("16"); // NOI18N
        jLabel16.setOpaque(true);
        jLabel16.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel16, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel16);
        jLabel16.setBounds(180, 80, 25, 25);

        jLabel23.setForeground(new java.awt.Color(51, 204, 0));
        jLabel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel23.setName("23"); // NOI18N
        jLabel23.setOpaque(true);
        jLabel23.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel23, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel23);
        jLabel23.setBounds(180, 280, 25, 25);

        jLabel18.setForeground(new java.awt.Color(51, 204, 0));
        jLabel18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel18.setName("18"); // NOI18N
        jLabel18.setOpaque(true);
        jLabel18.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel18, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel18);
        jLabel18.setBounds(180, 120, 25, 25);

        jLabel17.setForeground(new java.awt.Color(51, 204, 0));
        jLabel17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel17.setName("17"); // NOI18N
        jLabel17.setOpaque(true);
        jLabel17.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel17, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel17);
        jLabel17.setBounds(230, 80, 25, 25);

        jLabel20.setForeground(new java.awt.Color(51, 204, 0));
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel20.setName("20"); // NOI18N
        jLabel20.setOpaque(true);
        jLabel20.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel20, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel20);
        jLabel20.setBounds(230, 240, 25, 25);

        jLabel15.setForeground(new java.awt.Color(51, 204, 0));
        jLabel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel15.setName("15"); // NOI18N
        jLabel15.setOpaque(true);
        jLabel15.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel15, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel15);
        jLabel15.setBounds(810, 280, 25, 25);

        jLabel22.setForeground(new java.awt.Color(51, 204, 0));
        jLabel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel22.setName("22"); // NOI18N
        jLabel22.setOpaque(true);
        jLabel22.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel22, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel22);
        jLabel22.setBounds(230, 280, 25, 25);

        jLabel21.setForeground(new java.awt.Color(51, 204, 0));
        jLabel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel21.setName("21"); // NOI18N
        jLabel21.setOpaque(true);
        jLabel21.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel21, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel21);
        jLabel21.setBounds(180, 240, 25, 25);

        jLabel19.setForeground(new java.awt.Color(51, 204, 0));
        jLabel19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel19.setName("19"); // NOI18N
        jLabel19.setOpaque(true);
        jLabel19.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel19, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel19);
        jLabel19.setBounds(230, 120, 25, 25);

        jLabel31.setForeground(new java.awt.Color(51, 204, 0));
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel31.setOpaque(true);
        jLabel31.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel31, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel31);
        jLabel31.setBounds(350, 120, 25, 25);

        jLabel39.setForeground(new java.awt.Color(51, 204, 0));
        jLabel39.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel39.setOpaque(true);
        jLabel39.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel39, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel39);
        jLabel39.setBounds(350, 80, 25, 25);

        jLabel42.setForeground(new java.awt.Color(51, 204, 0));
        jLabel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel42.setOpaque(true);
        jLabel42.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel42, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel42);
        jLabel42.setBounds(300, 120, 25, 25);

        jLabel29.setForeground(new java.awt.Color(51, 204, 0));
        jLabel29.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel29.setOpaque(true);
        jLabel29.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel29, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel29);
        jLabel29.setBounds(300, 240, 25, 25);

        jLabel10.setForeground(new java.awt.Color(51, 204, 0));
        jLabel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel10.setName("10"); // NOI18N
        jLabel10.setOpaque(true);
        jLabel10.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel10, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel10);
        jLabel10.setBounds(470, 120, 25, 25);

        jLabel30.setForeground(new java.awt.Color(51, 204, 0));
        jLabel30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel30.setOpaque(true);
        jLabel30.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel30, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel30);
        jLabel30.setBounds(300, 280, 25, 25);

        jLabel9.setForeground(new java.awt.Color(51, 204, 0));
        jLabel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel9.setName("9"); // NOI18N
        jLabel9.setOpaque(true);
        jLabel9.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel9, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel9);
        jLabel9.setBounds(530, 120, 25, 25);

        jLabel40.setForeground(new java.awt.Color(51, 204, 0));
        jLabel40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel40.setOpaque(true);
        jLabel40.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel40, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel40);
        jLabel40.setBounds(300, 80, 25, 25);

        jLabel28.setForeground(new java.awt.Color(51, 204, 0));
        jLabel28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel28.setOpaque(true);
        jLabel28.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel28, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel28);
        jLabel28.setBounds(770, 280, 25, 25);

        jLabel38.setForeground(new java.awt.Color(51, 204, 0));
        jLabel38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel38.setOpaque(true);
        jLabel38.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel38, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel38);
        jLabel38.setBounds(770, 240, 25, 25);

        jLabel37.setForeground(new java.awt.Color(51, 204, 0));
        jLabel37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel37.setOpaque(true);
        jLabel37.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel37, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel37);
        jLabel37.setBounds(580, 120, 25, 25);

        jLabel11.setForeground(new java.awt.Color(51, 204, 0));
        jLabel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel11.setName("11"); // NOI18N
        jLabel11.setOpaque(true);
        jLabel11.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel11, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel11);
        jLabel11.setBounds(420, 120, 25, 25);

        jLabel14.setForeground(new java.awt.Color(51, 204, 0));
        jLabel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel14.setName("14"); // NOI18N
        jLabel14.setOpaque(true);
        jLabel14.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel14, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel14);
        jLabel14.setBounds(350, 280, 25, 25);

        jLabel12.setForeground(new java.awt.Color(51, 204, 0));
        jLabel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel12.setName("12"); // NOI18N
        jLabel12.setOpaque(true);
        jLabel12.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel12, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel12);
        jLabel12.setBounds(350, 240, 25, 25);

        jLabel13.setForeground(new java.awt.Color(51, 204, 0));
        jLabel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel13.setName("13"); // NOI18N
        jLabel13.setOpaque(true);
        jLabel13.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel13, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel13);
        jLabel13.setBounds(460, 240, 25, 25);

        jLabel48.setForeground(new java.awt.Color(51, 204, 0));
        jLabel48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel48.setOpaque(true);
        jLabel48.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel48, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel48);
        jLabel48.setBounds(700, 80, 25, 25);

        jLabel49.setForeground(new java.awt.Color(51, 204, 0));
        jLabel49.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel49.setOpaque(true);
        jLabel49.setPreferredSize(new java.awt.Dimension(25, 25));
        jLayeredPane2.setLayer(jLabel49, javax.swing.JLayeredPane.DRAG_LAYER);
        jLayeredPane2.add(jLabel49);
        jLabel49.setBounds(650, 120, 25, 25);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(statusPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(statusPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(5, 5, 5)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if((portField.getText().length()>0) && (hostField.getText().length()>0)){
            try{
                this.mancala = new Mancala(new Socket(hostField.getText(),Integer.parseInt(portField.getText())), this);
                Thread t = new Thread(this.mancala);
                t.start();
                this.onlineCheckbox.setSelected(true);
                this.playerLabel.setText(this.mancala.getPlayer());
                //Adicionando movimento depois do cliente ser criado.
                this.addMovement(this.pieces);
                this.hostNameLabel.setText(this.mancala.getHostName());
            } catch (IOException ex) {
                Logger.getLogger(Board.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void chatTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatTextFieldActionPerformed
        // TODO add your handling code here:
        this.mancala.sendChatMsg(this.mancala.getPlayer()+":"+this.chatTextField.getText());
        this.chatTextField.setText("");
    }//GEN-LAST:event_chatTextFieldActionPerformed

    private void restartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restartButtonActionPerformed
        // TODO add your handling code here:
        this.resetBoard();
        this.mancala.sendChatMsg("Player "+this.mancala.getPlayer()+" reiniciou o seu tabuleiro.");
        
    }//GEN-LAST:event_restartButtonActionPerformed

    private void endTurnButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endTurnButtonActionPerformed
        // TODO add your handling code here:
        //Envia pro server que eu terminei meu turno
        this.mancala.changeTurn();
    }//GEN-LAST:event_endTurnButtonActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.mancala.sendChatMsg("Player "+this.mancala.getPlayer()+" rendeu-se.");
        this.mancala.changeTurn();
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField chatTextField;
    private javax.swing.JButton endTurnButton;
    private javax.swing.JTextField hostField;
    private javax.swing.JLabel hostNameLabel;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private mancala.MainPanel mainPanel1;
    private javax.swing.JCheckBox onlineCheckbox;
    private javax.swing.JLabel playerLabel;
    private javax.swing.JTextField portField;
    private javax.swing.JButton restartButton;
    private javax.swing.JPanel statusPanel;
    private javax.swing.JLabel turnLabel;
    // End of variables declaration//GEN-END:variables
}
