/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mancala.Panels;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author iago-
 */
public class RightPanel extends javax.swing.JPanel {
    
    private final String boardRight = "/resources/MancalaRight.png";
    private Image right;
    private ImageIcon ii;

    /**
     * Creates new form RightPanel
     */
    public RightPanel() {
        initComponents();
        this.loadImage(this.boardRight);
        this.initPanel();
    }
    
    @Override
    public void paintComponent(Graphics g){
        g.drawImage(this.right, 0, 0, this);
    }
    
    private void loadImage(String file){
        ii = new ImageIcon(getClass().getResource(file));
        this.right = ii.getImage();
    }
    
    private void initPanel(){
        int w = ii.getIconWidth();
        int h = ii.getIconHeight();
        setPreferredSize(new Dimension(w,h));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
